[package]
name = "advent_of_code"
version = "42.42.42"
edition = "2024"

[dependencies]
colored = "2.1.0"

aoc_solvers = { path = "aoc_solvers" }
helpers = { path = "helpers" }
proc_macros = { path = "proc_macros" }

[workspace]
members = [
    "aoc_solvers",
    "helpers",
    "proc_macros",
]
